version: "2"

services:
  pingcentral:
    image: pricecs/pingcentral:1.0.1
    # Volumes used to inject initial data until a DevOps method is available
    # These folders should be created from a `git pull` of this repo
    volumes:
      - ./pingcentral/volumes/conf:/opt/out/instance/conf
      - ./pingcentral/volumes/h2-data/pingcentral.mv.db:/opt/out/instance/h2-data/pingcentral.mv.db
    ports:
      - 9022:9022
    networks:
      - pingnet

  pingfederate:
    image: pingidentity/pingfederate:edge
    command: wait-for pingdirectory:389 -t 300 -- entrypoint.sh start-server
    environment:
      - SERVER_PROFILE_URL=https://github.com/pkirubakaran/Profile-PingCentral.git
      - SERVER_PROFILE_PATH=pingfed
      - SERVER_PROFILE_PARENT=BASELINE
      - SERVER_PROFILE_BASELINE_URL=https://github.com/pkirubakaran/Profile-PF-Base.git
      - SERVER_PROFILE_BASELINE_PATH=pingfed
    env_file:
      # Configuration file created when setup.sh (Getting-started project root directory) is first run to source
      # devops user/key details for evaluation licenses and for docker image/git tags
      - ~/.pingidentity/devops
      - ./env_vars
    # Example: Examples below for mounting local directories for inbound server profile and persisting
    #          server build.  The local /opt/out directory must be empty when building new server
    #             /opt/out - Resulting server build
    #             /opt/in  - Inbound server-profile detail in liue of SERVER_PROFILE_URL (must be commented out)
    #volumes:
    #   - ${HOME}/projects/devops/volumes/simple-sync.pingfederate:/opt/out
    #   - ${HOME}/projects/devops/pingidentity-server-profiles/baseline/pingfederate:/opt/in
    ports:
      - 9031:9031
      - 9999:9999
    networks:
      - pingnet

  pingdirectory:
    image: pingidentity/pingdirectory:edge
    environment:
      - SERVER_PROFILE_URL=https://github.com/pkirubakaran/Profile-PingCentral.git
      - SERVER_PROFILE_PATH=pingdir
      - SERVER_PROFILE_PARENT=BASELINE
      - SERVER_PROFILE_BASELINE_URL=https://github.com/pkirubakaran/Profile-PD-Base.git
      - SERVER_PROFILE_BASELINE_PATH=pingdir
    env_file:
      - ~/.pingidentity/devops
      - ./env_vars
      #volumes:
    #   - ${HOME}/projects/devops/volumes/simple-sync.pingdirectory:/opt/out
    #   - ${HOME}/projects/devops/pingidentity-server-profiles/baseline/pingdirectory:/opt/in

    ports:
      - 1636:636
      - 1443:443
    networks:
      - pingnet
                    
  pingdataconsole:
    image: pingidentity/pingdataconsole:edge
    ports:
      - 8443:8443
    networks:
      - pingnet

networks:
    pingnet:
