version: "2"

services:
  pingcentral:
    image: pricecs/pingcentral:1.0.1
    volumes:
            - ./pingcentral/volumes/conf:/opt/out/instance/conf
            - ./pingcentral/volumes/h2-data/pingcentral.mv.db:/opt/out/instance/h2-data/pingcentral.mv.db
    ports:
      - 9022:9022
    networks:
      - pingnet

  pingfederate-prod:
    image: pingidentity/pingfederate:latest
    command: wait-for pingdirectory:389 -t 300 -- entrypoint.sh start-server
    env_file:
       - ~/.pingidentity/devops
       - ./env_vars
    volumes:
      - ./pf-prod/volumes/:/opt/out
    ports:
      - 9031:9031
      - 9999:9999
    networks:
      - pingnet

  pingfederate-qa:
    image: pingidentity/pingfederate:latest
    command: wait-for pingdirectory:389 -t 300 -- entrypoint.sh start-server
    env_file:
      - ~/.pingidentity/devops
      - ./env_vars
    volumes:
      - ./pf-qa/volumes/:/opt/out  
    ports:
      - 9032:9031
      - 9998:9999
    networks:
      - pingnet

  pingdirectory:
    image: pingidentity/pingdirectory:latest
    environment:
      - SERVER_PROFILE_URL=https://github.com/pkirubakaran/Profile-PingCentral.git
      - SERVER_PROFILE_PATH=pingdir
      - SERVER_PROFILE_PARENT=BASELINE
      - SERVER_PROFILE_BASELINE_URL=https://github.com/pkirubakaran/Profile-PD-Base.git
      - SERVER_PROFILE_BASELINE_PATH=pingdir
    env_file:
      - ~/.pingidentity/devops
      - ./env_vars
    ports:
      - 1636:636
      - 1443:443
    networks:
      - pingnet
                    
  pingdataconsole:
    image: pingidentity/pingdataconsole:latest
    ports:
      - 8443:8443
    networks:
      - pingnet
 
networks:
        pingnet:
